### ISSUE TITLE
[PE-D][Tester D] Wrong Error Handling

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2103T-W12-3/tp#232] opened 2024-04-05 21:05 UTC
Perhaps changing the error message to correctly identify the mistake for edit command

![image.png](https://raw.githubusercontent.com/felixchanyy/ped/main/files/5d3f4769-f5ca-40c7-bc6e-af1e731b019d.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: felixchanyy/ped#8

**Comment by aureliony** [comment] 2024-04-06 06:34
Duplicate of #218

**Closed by aureliony** 2024-04-06 06:34 UTC
Labels: severity.Low, type.duplicateBug
