### ISSUE TITLE
[PE-D][Tester A] Inconsistency in UG when introducing Commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-3/tp#204] opened 2024-04-05 18:14 UTC
The example command does not correspond to the format given.

In the example, there is a prefix "o\\", however this same prefix cannot be seen in the format given.

![image.png](https://raw.githubusercontent.com/Apzure/ped/main/files/cbfe5d05-0f42-47a3-a9bd-7722ac9ca795.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Apzure/ped#4

**Comment by aureliony** [comment] 2024-04-05 18:17
Duplicate of #190.

**Closed** 2024-04-05 19:37 UTC
Labels: severity.Low, type.duplicateBug
