### ISSUE TITLE
[PE-D][Tester A] Phrasing clarity about "Multiple assets can be specified. For example, a valid option is a\asset1 a\asset2 a\asset3 ."

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2103T-W12-3/tp#238] opened 2024-04-05 21:16 UTC
In the description of the asset field, it states "Multiple assets can be specified. For example, a valid option is a\asset1 a\asset2 a\asset3 ."

It is not clear what you are specifying the assets to, or what the command actually means or does in this context.

![image.png](https://raw.githubusercontent.com/Apzure/ped/main/files/b68b0842-81d0-44df-aca8-5e4a26ebcad4.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Apzure/ped#14

**Comment by aureliony** [comment] 2024-04-06 06:15
Duplicate of #205

**Closed** 2024-04-06 06:16 UTC
Labels: severity.Low, type.duplicateBug
